name: limited_video_recorder
description: "A Flutter plugin for video recording with file size, duration, resolution, and bitrate limits."
version: 0.0.1
homepage: https://github.com/sgsm74/limited_video_recorder
repository: https://github.com/sgsm74/limited_video_recorder
issue_tracker: https://github.com/sgsm74/limited_video_recorder/issues

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  video_compress: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ir.saeedqasemi.limited_video_recorder
        pluginClass: LimitedVideoRecorderPlugin
      ios:
        pluginClass: LimitedVideoRecorderPlugin
